function chara(name,img,flag,num){
    this.name = name;
    this.img = img;
    this.flag = flag;
    this.num = num;
};

var charas = new Array();
charas.push(new chara("アカリ", 'img/akari.PNG', true,1));
charas.push(new chara("アキノ", 'img/akino.PNG',true,1));
charas.push(new chara("アンナ",' img/annna.PNG',true,1));
charas.push(new chara("アオイ",'img/aoi.PNG',true,1));
charas.push(new chara("アヤネ",'img/ayane.PNG',false,1));
charas.push(new chara("アユミ",'img/ayumi.PNG',false,1));
charas.push(new chara("クリスティーナ",'img/christina.PNG',false,1));
charas.push(new chara("エリコ",'img/eriko.PNG',false,1));
charas.push(new chara("ハツネ",'img/hatsune.PNG',false,1));
charas.push(new chara("ヒヨリ",'img/hiyori.PNG',false,1));
charas.push(new chara("イオ",'img/io.PNG',false,1));
charas.push(new chara("イリヤ",'img/iriya.PNG',false,1));
charas.push(new chara("カオリ",'img/kaori.PNG',false,1));
charas.push(new chara("カスミ",'img/kasumi.PNG',false,1));
charas.push(new chara("カヤ",'img/kaya.PNG',false,1));
charas.push(new chara("コッコロ",'img/kokkoro.PNG',false,1));
charas.push(new chara("クロエ",'img/kuroe.PNG',false,1));
charas.push(new chara("クルミ",'img/kurumi.PNG',false,1));
charas.push(new chara("クウカ",'img/kuuka.PNG',false,1));
charas.push(new chara("キャル",'img/kyaru.PNG',false,1));
charas.push(new chara("キョウカ",'img/kyouka.PNG',false,1));
charas.push(new chara("マヒル",'img/mahiru.PNG',false,1));
charas.push(new chara("マホ",'img/maho.PNG',false,1));
charas.push(new chara("マコト",'img/makoto.PNG',false,1));
charas.push(new chara("マツリ",'img/matsuri.PNG',false,1));
charas.push(new chara("ミフユ",'img/mifuyu.PNG',false,1));
charas.push(new chara("ミミ",'img/mimi.PNG',false,1));
charas.push(new chara("ミサキ",'img/misaki.PNG',false,1));
charas.push(new chara("ミサト",'img/misato.PNG',false,1));
charas.push(new chara("ミソギ",'img/misogi.PNG',false,1));
charas.push(new chara("ミツキ",'img/mitsuki.PNG',false,1));
charas.push(new chara("ミヤコ",'img/miyako.PNG',false,1));
charas.push(new chara("モニカ",'img/monica.PNG',false,1));
charas.push(new chara("ムイミ",'img/muimi.PNG',false,1));
charas.push(new chara("ナナカ",'img/nanaka.PNG',false,1));
charas.push(new chara("ネネカ",'img/neneka.PNG',false,1));
charas.push(new chara("ニノン",'img/ninon.PNG',false,1));
charas.push(new chara("ノゾミ",'img/nozomi.PNG',false,1));
charas.push(new chara("ペコリーヌ",'img/pecorine.PNG',false,1));
charas.push(new chara("レイ",'img/rei.PNG',false,1));
charas.push(new chara("リマ",'img/rima.PNG',false,1));
charas.push(new chara("リン",'img/rin.PNG',false,1));
charas.push(new chara("リノ",'img/rino.PNG',false,1));
charas.push(new chara("サレン",'img/saren.PNG',false,1));
charas.push(new chara("シノブ",'img/shinobu.PNG',false,1));
charas.push(new chara("シオリ",'img/shiori.PNG',false,1));
charas.push(new chara("シズル",'img/shizuru.PNG',false,1));
charas.push(new chara("スズメ",'img/suzume.PNG',false,1));
charas.push(new chara("スズナ",'img/suzuna.PNG',false,1));
charas.push(new chara("タマキ",'img/tamaki.PNG',false,1));
charas.push(new chara("チカ",'img/tika.PNG',false,1));
charas.push(new chara("トモ",'img/tomo.PNG',false,1));
charas.push(new chara("ツムギ",'img/tumugi.PNG',false,1));
charas.push(new chara("ヨリ",'img/yori.PNG',false,1));
charas.push(new chara("ユイ",'img/yui.PNG',false,1));
charas.push(new chara("ユカリ",'img/yukari.PNG',false,1));
charas.push(new chara("ユキ",'img/yuki.PNG',false,1));
charas.push(new chara("ジュン",'img/zyun.PNG',false,1));
